# Generated by Django 5.2.6 on 2025-09-22 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_rename_payments_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("pending", "Ожидает оплаты"),
                    ("succeeded", "Оплачено"),
                    ("canceled", "Отменено"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Статус платежа",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="stripe_payment_url",
            field=models.URLField(
                blank=True,
                max_length=500,
                null=True,
                verbose_name="Ссылка на оплату Stripe",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="stripe_session_id",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="ID сессии Stripe"
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[("card", "Картой"), ("transfer", "Перевод на счет")],
                max_length=10,
                verbose_name="Способ оплаты",
            ),
        ),
    ]
