# Generated by Django 5.2.6 on 2025-09-22 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_payment_payment_status_payment_stripe_payment_url_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="payment_status",
        ),
    ]
