# Generated by Django 5.2.6 on 2025-09-20 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0003_subscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Дата обновления подписки"
            ),
        ),
    ]
