# Generated by Django 5.2.6 on 2025-09-22 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0004_subscription_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                default=500.0,
                help_text="Укажите цену курса",
                max_digits=10,
                verbose_name="Цена курса",
            ),
        ),
    ]
