# Generated by Django 5.2.6 on 2025-09-25 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0005_course_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="last_updated",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Время последнего обновления курса",
                verbose_name="Время последнего обновления",
            ),
        ),
    ]
