# Generated by Django 5.2.6 on 2025-09-26 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0006_course_last_updated"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="last_updated",
        ),
    ]
