# Generated by Django 5.2.6 on 2025-09-26 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0007_remove_course_last_updated"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="last_updated",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Время последнего обновления курса",
                verbose_name="Время последнего обновления",
            ),
        ),
    ]
